<a href="https://colab.research.google.com/github/lucaspereira25-lps/LucasPereira-CalculoNum-rico/blob/main/Sistemas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# ==========================================
# PARTE 1 — Conceitos e Resolução Manual
# ==========================================

print("=== EXERCÍCIO 1: FORMA MATRICIAL (Ax = b) ===")

# Item 1a
A_1a = np.array([[2, 1], [1, -3]])
b_1a = np.array([7, -5])
print("1a) Matriz A:\n", A_1a)
print("    Vetor b:", b_1a)

# Item 1b
A_1b = np.array([[1, 2, -1], [3, -1, 2], [2, 1, 1]])
b_1b = np.array([2, 9, 7])
print("\n1b) Matriz A:\n", A_1b)
print("    Vetor b:", b_1b)


# ==========================================
# PARTE 3 & EXERCÍCIO 2 — Eliminação de Gauss
# ==========================================

def eliminacao_gauss(A, b, mostrar_passos=True):
    """
    Algoritmo de Eliminação de Gauss sem pivoteamento.
    Retorna a solução do sistema e exibe as etapas da matriz aumentada.
    """
    A = np.array(A, dtype=float)
    b = np.array(b, dtype=float).reshape(-1, 1)
    n = len(b)

    # Formar a matriz aumentada [A|b]
    Ab = np.hstack([A, b])

    if mostrar_passos:
        print("\nMatriz aumentada inicial [A|b]:")
        print(np.round(Ab, 4))

    # Eliminação dos elementos abaixo do pivô
    for i in range(n):
        for k in range(i + 1, n):
            fator = Ab[k, i] / Ab[i, i]
            Ab[k, i:] -= fator * Ab[i, i:]
            if mostrar_passos:
                print(f"\nApós eliminar elemento na linha {k+1}, coluna {i+1}:")
                print(np.round(Ab, 4))

    # Substituição regressiva
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = (Ab[i, -1] - np.dot(Ab[i, i+1:n], x[i+1:n])) / Ab[i, i]

    return x

print("\n\n=== EXERCÍCIO 2 & 4: ELIMINAÇÃO DE GAUSS (PASSO A PASSO) ===")
A_ex2 = [[2, 1, -1],
         [-3, -1, 2],
         [-2, 1, 2]]
b_ex2 = [8, -11, -3]

sol_gauss = eliminacao_gauss(A_ex2, b_ex2, mostrar_passos=True)
sol_numpy = np.linalg.solve(A_ex2, b_ex2)

print("\n--- Validação ---")
print("Solução via Eliminação de Gauss:", sol_gauss)
print("Solução via numpy.linalg.solve:", sol_numpy)


# ==========================================
# PARTE 2 — Propriedades e Análise de Soluções
# ==========================================

print("\n\n=== EXERCÍCIO 3: ANÁLISE DO NÚMERO DE SOLUÇÕES ===")

sistemas_ex3 = {
    "3a": (np.array([[1, 1], [2, 2]], dtype=float), np.array([3, 6], dtype=float)),
    "3b": (np.array([[1, 1], [2, 2]], dtype=float), np.array([3, 7], dtype=float)),
    "3c": (np.array([[1, 1], [2, -1]], dtype=float), np.array([3, 0], dtype=float))
}

for item, (A, b) in sistemas_ex3.items():
    Ab = np.hstack([A, b.reshape(-1, 1)])
    posto_A = np.linalg.matrix_rank(A)
    posto_Ab = np.linalg.matrix_rank(Ab)
    n_variaveis = A.shape[1]

    print(f"\nItem {item}:")
    print(f"  - Posto(A): {posto_A}")
    print(f"  - Posto([A|b]): {posto_Ab}")

    if posto_A < posto_Ab:
        print("  - Classificação: NENHUMA SOLUÇÃO (Sistema Impossível)")
    elif posto_A == posto_Ab == n_variaveis:
        print("  - Classificação: SOLUÇÃO ÚNICA (Sistema Possível e Determinado)")
    else:
        print("  - Classificação: INFINITAS SOLUÇÕES (Sistema Possível e Indeterminado)")


# ==========================================
# PARTE 4 — Aplicação: Balanço Térmico
# ==========================================

print("\n\n=== EXERCÍCIO 5: MODELO DE BALANÇO TÉRMICO ===")
A_term = np.array([[4, -1, 0],
                   [-1, 4, -1],
                   [0, -1, 3]], dtype=float)
b_term = np.array([15, 10, 10], dtype=float)

T = eliminacao_gauss(A_term, b_term, mostrar_passos=False)

print("\nTemperaturas encontradas (T1, T2, T3):", T)

=== EXERCÍCIO 1: FORMA MATRICIAL (Ax = b) ===
1a) Matriz A:
 [[ 2  1]
 [ 1 -3]]
    Vetor b: [ 7 -5]

1b) Matriz A:
 [[ 1  2 -1]
 [ 3 -1  2]
 [ 2  1  1]]
    Vetor b: [2 9 7]


=== EXERCÍCIO 2 & 4: ELIMINAÇÃO DE GAUSS (PASSO A PASSO) ===

Matriz aumentada inicial [A|b]:
[[  2.   1.  -1.   8.]
 [ -3.  -1.   2. -11.]
 [ -2.   1.   2.  -3.]]

Após eliminar elemento na linha 2, coluna 1:
[[ 2.   1.  -1.   8. ]
 [ 0.   0.5  0.5  1. ]
 [-2.   1.   2.  -3. ]]

Após eliminar elemento na linha 3, coluna 1:
[[ 2.   1.  -1.   8. ]
 [ 0.   0.5  0.5  1. ]
 [ 0.   2.   1.   5. ]]

Após eliminar elemento na linha 3, coluna 2:
[[ 2.   1.  -1.   8. ]
 [ 0.   0.5  0.5  1. ]
 [ 0.   0.  -1.   1. ]]

--- Validação ---
Solução via Eliminação de Gauss: [ 2.  3. -1.]
Solução via numpy.linalg.solve: [ 2.  3. -1.]


=== EXERCÍCIO 3: ANÁLISE DO NÚMERO DE SOLUÇÕES ===

Item 3a:
  - Posto(A): 1
  - Posto([A|b]): 1
  - Classificação: INFINITAS SOLUÇÕES (Sistema Possível e Indeterminado)

Item 3b:
  - Posto(A): 1
 